# The following workflow provides an opinionated template you can customize for your own needs.
#
# If you are not an Octopus user, the "Push to Octopus", "Generate Octopus Deploy build information",
# and "Create Octopus Release" steps can be safely deleted.
#
# To configure Octopus, set the OCTOPUS_API_TOKEN secret to the Octopus API key, and
# set the OCTOPUS_SERVER_URL secret to the Octopus URL.
#
# Double check the "project" and "deploy_to" properties in the "Create Octopus Release" step
# match your Octopus projects and environments.
#
# Get a trial Octopus instance from https://octopus.com/start

permissions:
  id-token: write
  checks: write
  contents: write

name: Go Build
'on':
  workflow_dispatch: {}
  push:
    paths-ignore:
      - '**/*.md'
jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        parallel: [10]
        index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Download JUnit Summary from Previous Workflow
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          name: junit-test-summary
          if_no_artifact_found: warn
          branch: main

      - name: Split integration tests
        id: test_split
        uses: hashicorp-forge/go-test-split-action@v1
        with:
          index: ${{ matrix.index }}
          total: ${{ matrix.parallel }}
          junit-summary: ./junit-test-summary.xml

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Clone the Terraform provider source
        run: git clone https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy.git
        shell: bash

      - name: Build the Terraform provider from source
        run: go build -o terraform-provider-octopusdeploy
        working-directory: terraform-provider-octopusdeploy

      - name: Override the location used by Terraform provider
        run: |-
          cat <<EOT >> ~/.terraformrc
          provider_installation {
              dev_overrides {
              "octopusdeploylabs/octopusdeploy" = "${{ github.workspace }}/terraform-provider-octopusdeploy"
            }
            direct {}
          }
          EOT

      - name: Go test
        shell: bash
        env:
          LICENSE: ${{ secrets.LICENSE }}
          ECR_ACCESS_KEY: ${{ secrets.ECR_ACCESS_KEY }}
          ECR_SECRET_KEY: ${{ secrets.ECR_SECRET_KEY }}
          GIT_CREDENTIAL: ${{ secrets.GIT_CREDENTIAL }}
          OCTOTESTSKIPINIT: false
          OCTODISABLEOCTOCONTAINERLOGGING: true
          OCTOTESTDUMPSTATE: true
          OCTOTESTDEFAULTSPACEID: Spaces-2
          GOMAXPROCS: 1
        run: |
          sudo apt install gotestsum
          gotestsum --junitfile node-summary.xml --format short-verbose -- -run "${{ steps.test_split.outputs.run }}" -timeout 0 ./...

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-summary-${{ matrix.index }}
          path: node-summary.xml
          retention-days: 1

  tests-combine-summaries:
    name: Combine Test Reports
    needs: [ tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Install junit-report-merger
        run: npm install -g junit-report-merger

      - name: Merge reports
        run: >
          jrm ./junit-test-summary.xml 
          "junit-test-summary-0/*.xml" 
          "junit-test-summary-1/*.xml" 
          "junit-test-summary-2/*.xml" 
          "junit-test-summary-3/*.xml" 
          "junit-test-summary-4/*.xml" 
          "junit-test-summary-5/*.xml" 
          "junit-test-summary-6/*.xml" 
          "junit-test-summary-7/*.xml" 
          "junit-test-summary-8/*.xml" 
          "junit-test-summary-9/*.xml"

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-summary
          path: ./junit-test-summary.xml

      - name: Report
        uses: dorny/test-reporter@v1
        with:
          name: Go Tests
          path: junit-test-summary.xml
          reporter: java-junit
          fail-on-error: 'true'

  build:
    runs-on: ubuntu-latest
    needs: [ tests-combine-summaries ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: 5.x
      - id: determine_version
        name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.15
        with:
          additionalArguments: /overrideconfig mode=Mainline
      - name: Install Octopus Deploy CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1
        with:
          version: latest
      - name: Install Dependencies
        run: go get ./...
        shell: bash
      - name: List Dependencies
        run: go list -m all > dependencies.txt
        shell: bash
      - name: Collect Dependencies
        uses: actions/upload-artifact@v3
        with:
          name: Dependencies
          path: dependencies.txt
#      - name: List Dependency Updates
#        run: go list -u -m -f "{{if .Update}}{{.}}{{end}}" all > dependencyUpdates.txt
#        shell: bash
      - name: Collect Dependency Updates
        uses: actions/upload-artifact@v3
        with:
          name: Dependencies Updates
          path: dependencyUpdates.txt
      - run: go build -ldflags="-X 'main.Version=${{ steps.determine_version.outputs.semVer }}'" -o octoterra_linux_amd64 cmd/octoterra.go
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
      - run: go build -ldflags="-X 'main.Version=${{ steps.determine_version.outputs.semVer }}'" -o octoterra_windows_amd64.exe cmd/octoterra.go
        env:
          GOOS: windows
          GOARCH: amd64
          CGO_ENABLED: 0
      - run: go build -ldflags="-X 'main.Version=${{ steps.determine_version.outputs.semVer }}'" -o octoterra_macos_amd64 cmd/octoterra.go
        env:
          GOOS: darwin
          GOARCH: amd64
          CGO_ENABLED: 0
      - run: go build -ldflags="-X 'main.Version=${{ steps.determine_version.outputs.semVer }}'" -o octoterra_macos_arm64 cmd/octoterra.go
        env:
          GOOS: darwin
          GOARCH: arm64
          CGO_ENABLED: 0
      - name: Tag Release
        uses: mathieudutour/github-tag-action@v6.1
        continue-on-error: true
        with:
          custom_tag: ${{ steps.determine_version.outputs.semVer }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        with:
          tag_name: ${{ steps.determine_version.outputs.semVer }}+run${{ github.run_number }}-attempt${{ github.run_attempt }}
          files: |
            octoterra_linux_amd64
            octoterra_windows_amd64.exe
            octoterra_macos_amd64
            octoterra_macos_arm64
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push latest
        if: ${{ steps.branch-name.outputs.current_branch == 'main' }}
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          tags: octopussamples/octoterra:latest
          build-args: Version=${{ steps.determine_version.outputs.semVer }}
      - name: Build and push versioned image
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          tags: octopussamples/octoterra:${{ steps.determine_version.outputs.semVer }}
          build-args: Version=${{ steps.determine_version.outputs.semVer }}
  build-windows:
    runs-on: windows-latest
    env:
      DOCKER_BUILDKIT: 0
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.5 # 1.20.6 breaks the tests: https://github.com/golang/go/issues/61431
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: 5.x
      - id: determine_version
        name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.15
        with:
          additionalArguments: /overrideconfig mode=Mainline
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: go build -ldflags="-X 'main.Version=${{ steps.determine_version.outputs.semVer }}'" -o octoterra_windows_amd64.exe cmd/octoterra.go
        env:
          GOOS: windows
          GOARCH: amd64
          CGO_ENABLED: 0
      - name: Build and push latest
        if: ${{ steps.branch-name.outputs.current_branch == 'main' }}
        run: |
          docker build --platform windows/amd64 . -f Dockerfile.windows -t octopussamples/octoterra-windows:latest
          docker push octopussamples/octoterra-windows:latest
      - name: Build and push
        if: ${{ steps.branch-name.outputs.current_branch == 'main' }}
        run: |
          docker build --platform windows/amd64 . -f Dockerfile.windows -t octopussamples/octoterra-windows:${{ steps.determine_version.outputs.semVer }}
          docker push octopussamples/octoterra-windows:${{ steps.determine_version.outputs.semVer }}
